language: python
sudo: false

env:
  - LUA="lua 5.1"
  - LUA="lua 5.2"
  - LUA="lua 5.3"
  - LUA="luajit 2.0"
  - LUA="luajit 2.1"

before_install:
  - pip install hererocks
  - pip install codecov
  - hererocks here --$LUA -r latest
  - source here/bin/activate
  - luarocks install busted
  - luarocks install cluacov
  - luarocks install luacheck

install:
  - luarocks make

script:
  - luacheck .
  - busted -c
  - if [[ "$LUA" == "lua 5.1" ]]; then
      luarocks install luabitop;
      busted -c;
      luarocks remove luabitop;
      luarocks install bit32;
      busted -c;
    elif [[ "$LUA" == "lua 5.2" ]]; then
      luarocks install luabitop;
      busted -c;
    fi

after_script:
  - luacov
  - codecov -f luacov.report.out -X gcov
